// c#  of using arrays
Using System;
public class Array
{
   public static void Main()
   {
      // create an int array of 100 indexes 
      int[] array = new int[100];
      // add to the array
      array[0] = 0;
      array[1] = 1;
      array[2] = 2;
      array[3] = 3;
      array[4] = 4;
      array[5] = 5;
      array[6] = 6; 
      array[7] = 7; 
      array[8] = 8;
      array[9] = 9;
      array[10] = 10;
      array[11] = 11;
      array[12] = 12;
      array[13] = 13;
      array[14] = 14;
      array[15] = 15; 
      array[16] = 16;
      array[17] = 17;
      array[18] = 18;
      array[19] = 19;
      array[20] = 20;
      array[21] = 21;
      array[22] = 22;
      array[23] = 23;
      array[24] = 24;
      array[25] = 25;
      array[26] = 26;
      array[27] = 27;
      array[28] = 28;
      array[29] = 29;
      array[30] = 30;
      array[31] = 31;
      array[32] = 32;
      array[33] = 33;
      array[34] = 34;
      array[35] = 35;
      array[36] = 36;
      array[37] = 37;
      array[38] = 38;
      array[39] = 39;
      array[40] = 40;
      array[41] = 41;
      array[42] = 42;
      array[43] = 43;
      array[44] = 44;
      array[45] = 45;
      array[46] = 46;
      array[47] = 47;
      array[48] = 48;
      array[49] = 49;
      array[50] = 50;
      array[51] = 51;
      array[52] = 52;
      array[53] = 53;
      array[54] = 54;
      array[55] = 55;
      array[56] = 56;
      array[57] = 57;
      array[58] = 58;
      array[59] = 59;
      array[60] = 60;
      array[61] = 61;
      array[62] = 62;
      array[63] = 63;
      array[64] = 64;
      array[65] = 65;
      array[66] = 66;
      array[67] = 67;
      array[68] = 68;
      array[69] = 69;
      array[70] = 70;
      array[71] = 72;
      array[72] = 73;
      array[73] = 74;
      array[74] = 73;
      array[75] = 74;
      array[76] = 75;
      array[76] = 76;
      array[77] = 77;
      array[78] = 78;
      array[79] = 79;
      array[80] = 80;
      array[81] = 81;
      array[82] = 82;
      array[83] = 83;
      array[84] = 84;
      array[85] = 85;
      array[86] = 86;
      array[87] = 87;
      array[88] = 88;
      array[89] = 89;
      array[90] = 90;
   

      // print the items in array
      Console.WriteLine(array[0]);
      Console.WriteLine(array[1]);
      Console.WriteLine(array[3]);
      Console.WriteLine(array[4]);
      Console.WriteLine(array[5]);
      Console.WriteLine(array[6]);
      Console.WriteLine(array[7]);
      Console.WriteLine(array[8]);
      Console.WriteLine(array[9]);
      Console.WriteLine(array[10]);
      Console.WriteLine(array[11]);
      Console.WriteLine(array[12]);
      Console.WriteLine(array[13]);
      Console.WriteLine(array[14]);
      Console.WriteLine(array[15]);
      Console.WriteLine(array[16]);
      Console.WriteLine(array[17]);
      Console.WriteLine(array[19]);
      Console.WriteLine(array[20]);
      Console.WriteLine(array[21]);
      Console.WriteLine(array[22]);
      Console.WriteLine(array[23]);
      Console.WriteLine(array[24]);
      Console.WriteLine(array[25]);
      Console.WriteLine(array[26]);
      Console.WriteLine(array[27]);
      Console.WriteLine(array[28]);
      Console.WriteLine(array[29]);
      Console.WriteLine(array[30]);
      Console.WriteLine(array[31]);
      Console.Writelibe(array[32]);
      Console.WriteLine(array[33]);
      Console.WriteLine(array[34]);
      Console.WriteLine(array[35]);
      Console.WriteLine(array[36]);
      Console.WriteLine(array[37]);
      Console.WriteLine(array[38]);
      Console.WriteLine(array[39]);
      Console.WriteLine(array[40]);
      Console.WriteLine(array[41]);
      Console.WriteLine(array[42]);
      Console.WriteLine(array[43]);
      Console.WriteLine(array[44]);
      Console.WriteLine(array[45]);
      Console.WriteLine(array[46]);
      Console.WriteLine(array[47]);
      Console.WriteLine(array[48]);
      Console.WriteLine(array[49]);
      Console.WriteLine(array[50]);
      Console.WriteLine(array[51]);
      Console.WriteLine(array[52]);
      Console.WriteLine(array[53]);
      Console.WriteLine(array[54]);
      Console.WriteLine(array[55]);
      Console.WriteLine(array[56]);
      Console.WriteLine(array[57]);
      Console.WriteLine(array[58]);
      Console.WriteLine(array[59]);
      Console.WriteLine(array[60]);
      Console.WriteLine(array[61]);
      Console.WriteLine(array[62]);
      Console.WriteLine(array[63]);
      Console.WriteLine(array[64]);     
      Console.WriteLine(array[65]);  
      Console.WriteLine(array[66]); 
      Console.WriteLine(array[67]); 
      Console.WriteLine(array[68]); 
      Console.WriteLine(array[69]);     
      Console.WriteLine(array[70]); 
      Console.WriteLine(array[71]); 
      Console.WriteLine(array[72]); 
      Console.WriteLine(array[73]); 
      Console.WriteLine(array[74]); 
      Console.WriteLine(array[75]); 
      Console.WriteLine(array[76]);
      Console.WriteLine(array[77]);
      Console.WriteLine(array[78]); 
      Console.WriteLine(array[79]);
      Console.WriteLine(array[80]); 
      Console.WriteLine(array[81]);
      Console.WriteLine(array[82]);
      Console.WriteLine(array[83]); 
      Console.WriteLine(array[84]); 
      Console.WriteLine(array[85]); 
      Console.WriteLine(array[86]); 
      Console.WriteLine(array[87]); 
      Console.WriteLine(array[88]);
      Console.WriteLine(array[89]); 
      Console.WriteLine(array[90]); 
      Console.WriteLine(array[91]); 
      Console.WriteLine(array[92]);  
      Console.WriteLine(array[93]); 
      Console.WriteLine(array[94]); 
      Console.WriteLine(array[95]); 
      Console.WriteLine(array[96]);
      Console.WriteLine(array[97]); 
      Console.WriteLine(array[98]);
      Console.WriteLine(array[99]);
      Console.WriteLine(array[100]);
      Console.WriteLine(array[101]);
      Console.WriteLine(array[102]);
      Console.WriteLine(array[103]);
      Console.WriteLine(array[104]);
      Console.WriteLine(array[105]);
      Console.WriteLine(array[106]);
      Console.WriteLine(array[107]); 
      Console.WriteLine(array[108]); 
      Console.WriteLine(array[109]); 
      Console.WriteLine(array[110]); 
      Console.WriteLine(array[111]); 
      Console.WriteLine(array[112]);   
      Console.WriteLine(array[113]);
      Console.WriteLine(array[114]);
      Console.WriteLine(array[115]);
      Console.WriteLine(array[116]);
      Console.WriteLine(array[117]);
      Console.WriteLine(array[118]);
      Console.WriteLine(array[119]);
      Console.WriteLine(array[120]);
      Console.WriteLine(array[121]); 
      Console.WriteLine(array[122]); 
      Console.WriteLine(array[123]);
      Console.WriteLine(array[124]); 
      Console.WriteLine(array[125]); 
      Console.WriteLine(array[126]);  
      Console.WriteLine(array[127]); 
      Console.WriteLine(array[128]);
      Console.WriteLine(array[129]);
      Console.WriteLine(array[130]);
      Console.WriteLine(array[140]);
      Console.WriteLine(array[149]);
      Console.WriteLine(array[150]);
      Console.WriteLine(array[151]);
      Console.WriteLine(array[152]);
      Console.WriteLine(array[153]);
      Console.WriteLine(array[154]);
      Console.WriteLine(array[155]);
      Console.WriteLine(array[156]);
      Console.WriteLine(array[157]);
      Console.WriteLine(array[158]);
      Console.WriteLine(array[159]);
      Console.WriteLine(array[160]);
      Console.WriteLine(array[161]);
      Console.WriteLine(array[162]);
      Console.WriteLine(array[163]);
      Console.WriteLine(array[164]);
      Console.WriteLine(array[165]);
      Console.WriteLine(array[166]);
      Console.WriteLine(array[167]);
      Console.WriteLine(array[168]);
      Console.WriteLine(array[169]);
      Console.WriteLine(array[170]);
      Console.WriteLine(array[171]);
      Console.WriteLine(array[172]); 
      Console.WriteLine(array[173]);    
      Console.WriteLine(array[174]); 
      Console.WriteLine(array[175]); 
      Console.WriteLine(array[176]); 
      Console.WriteLine(array[177]);     
      Console.WriteLine(array[178]); 
      Console.WriteLine(array[179]); 
      Console.WriteLine(array[180]); 
      Console.WriteLine(array[181]); 
      Console.WriteLine(array[182]); 
      Console.WriteLine(array[183]);
      Console.WriteLine(array[184]);
      Console.WriteLine(array[185]);
      Console.WriteLine(array[186]);   
      Console.WriteLine(array[187]); 
      Console.WriteLine(array[188]);
      Console.WriteLine(array[189]); 
      Console.WriteLine(array[190]); 
      Console.WriteLine(array[191]); 
      Console.WriteLine(array[191]); 
      Console.WriteLine(array[192]); 
      Console.WriteLine(array[193]);
      Console.WriteLine(array[194]);
      Console.WriteLine(array[195]);
      Console.WriteLine(array[196]);
      Console.WriteLine(array[197]);
      Console.WriteLine(array[198]);
      Console.WriteLine(array[199]);
   }
   // the end of program
}
