Using System;
public class Array
{
   public static void Main()
   {
      // create an int array of 50 indexes 
      int[] array = new int[50];
      array[0] = 0;
      array[1] = 1;
      array[2] = 2;
      array[3] = 3;
      array[4] = 4;
      array[5] = 10;
      array[6] = 6; 
      array[7] = 78; 
      array[8] = 60;
      array[9] = 29;
      array[10] = 10;
      array[11] = 61;
      array[12] = 12;
      array[13] = 81;
      array[14] = 14;
      array[15] = 47; 
      array[16] = 16;
      array[17] = 57;
      array[18] = 18;
      array[19] = 19;
      array[20] = 56;
      array[21] = 32;
      array[22] = 65;
      array[23] = 3;
      array[24] = 62;
      array[25] = 32;
      array[26] = 26;
      array[27] = 67;
      array[28] = 28;
      array[29] = 77;
      array[30] = 8;
      array[31] = 11;
      array[32] = 91;
      array[33] = 3;
      array[34] = 17;
      array[35] = 31;
      array[36] = 24;
      array[37] = 38;
      array[38] = 52;
      array[39] = 26;
      array[40] = 81;
      array[41] = 9;
      array[42] = 35;
      array[43] = 52;
      array[44] = 71;
      array[45] = 12;
      array[46] = 53;
      array[47] = 73;
      array[48] = 62;
      array[49] = 74;
   
      // print the items in array
      Console.WriteLine(array[0]);
      Console.WriteLine(array[1]);
      Console.WriteLine(array[2]);
      Console.WriteLine(array[3]);
      Console.WriteLine(array[4]);
      Console.WriteLine(array[5]);
      Console.WriteLine(array[6]);
      Console.WriteLine(array[7]);
      Console.WriteLine(array[8]);
      Console.WriteLine(array[9]);
      Console.WriteLine(array[10]);
      Console.WriteLine(array[11]);
      Console.WriteLine(array[12]);
      Console.WriteLine(array[13]);
      Console.WriteLine(array[14]);
      Console.WriteLine(array[15]);
      Console.WriteLine(array[16]);
      Console.WriteLine(array[17]);
      Console.WriteLine(array[18]);
      Console.WriteLine(array[19]);
      Console.WriteLine(array[20]);
      Console.WriteLine(array[21]);
      Console.WriteLine(array[22]);
      Console.WriteLine(array[23]);
      Console.WriteLine(array[24]);
      Console.WriteLine(array[25]);
      Console.WriteLine(array[26]);
      Console.WriteLine(array[27]);
      Console.WriteLine(array[28]);
      Console.WriteLine(array[29]);
      Console.WriteLine(array[30]);
      Console.WriteLine(array[31]);
      Console.WriteLine(array[32]);
      Console.WriteLine(array[33]);
      Console.WriteLine(array[34]);
      Console.WriteLine(array[35]);
      Console.WriteLine(array[36]);
      Console.WriteLine(array[37]);
      Console.WriteLine(array[38]);
      Console.WriteLine(array[39]);
      Console.WriteLine(array[40]);
      Console.WriteLine(array[41]);
      Console.WriteLine(array[42]);
      Console.WriteLine(array[43]);
      Console.WriteLine(array[44]);
      Console.WriteLine(array[45]);
      Console.WriteLine(array[46]);
      Console.WriteLine(array[47]);
      Console.WriteLine(array[48]); 
      Console.WriteLine(array[49]);  
   }
   // the end of program
}
